### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by OksanaMir** [BaraKalvo/ukol1#1]
Ahoj
Jsi moc šikovná. Dokázala jsi vytvořit vícestránkový web:) Skvěla práce 
# Co by šlo výlepšit
### HTML

- [x]  `<html lang="en">` nahradit `<html lang="cs">`

### dovednosti.html

- [x] Třidy se nesmí začínat velkým písmenem 

```<td class="A"></td>
      <td class="H"></td>
       <td class="O"></td>
        <td class="J"></td>
```

### CSS
1. 

- [x] Selektor `html` přehoď před  ` body`

2. 

- [x] Pokud všechny 4 hodnoty jsou stejné, můžeme zkrátit `border-radius: 20px 20px 20px 20px;` =>  `border-radius: 20px;`

3. 

- [x] `clear: both;` neděla na footru nic. Není tam před footrem prvku s nastaveným obtékáním 

4. 

- [x] Pro background existuje shorthand. `background: white url(obrazky/A.png) no-repeat;`  místo

```
background-image: url(obrazky/A.png);
    background-repeat: no-repeat;
    background-color: white;
```
A pro všechna písmena to stejní.

**Comment by BaraKalvo** [comment]
Ahoj, moc děkuji za komentář a za čas, který jsi tomu věnovala :-) Připomínky zapracuji do kódu :-)

**Comment by BaraKalvo** [comment]
Ahoj, upravila jsem kód podle komentáře :-)
